### ISSUE TITLE
dist utils KeyError "LOCAL_RANK"

### ISSUE THREAD

**Issue by LimChaeYeon1003** [Theodore-PKU/MC-DDPM#1]
'LOCAL_RANK'

During handling of the above exception, another exception occurred:

  File "/hdd1/MC_DDPM/utils/dist_util.py", line 22, in setup_dist
    th.cuda.set_device(int(os.environ["LOCAL_RANK"]))
  File "/hdd1/MC_DDPM/kspace_train.py", line 26, in main
    is_distributed, rank = dist_util.setup_dist()
  File "/hdd1/MC_DDPM/kspace_train.py", line 98, in <module>
    main()

i have some problem os.environ haven't key "LOCAL_RANK" how to bring it?

I want use multi GPU can you help me?

**Comment by CarinaL99** [comment]
I met the same problem. How did you solve it?

**Comment by LimChaeYeon1003** [comment]
I use to code with python $ python torch.distributed.launch python/path

**Comment by CarinaL99** [comment]
> I use to code with python $ python torch.distributed.launch python/path

Thanks!
